export const Currencies = [
    {	label:	"	Albania	(	ALL	)	"	,	value:	"	ALL	"	}	,
    {	label:	"	Algeria	(	ALL	)	"	,	value:	"	ALL	"	}	,
    {	label:	"	Angola	(	AOA	)	"	,	value:	"	AOA	"	}	,
    {	label:	"	Argentina	(	ARS	)	"	,	value:	"	ARS	"	}	,
    {	label:	"	Armenia	(	AMD	)	"	,	value:	"	AMD	"	}	,
    {	label:	"	Australia	(	AUD	)	"	,	value:	"	AUD	"	}	,
    {	label:	"	Austria	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Azerbaijan	(	AZN	)	"	,	value:	"	AZN	"	}	,
    {	label:	"	Bahrain	(	BHD	)	"	,	value:	"	BHD	"	}	,
    {	label:	"	Barbados	(	BBD	)	"	,	value:	"	BBD	"	}	,
    {	label:	"	Belarus	(	BYN	)	"	,	value:	"	BYN	"	}	,
    {	label:	"	Belgium	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Bermuda	(	BMD	)	"	,	value:	"	BMD	"	}	,
    {	label:	"	Bolivia	(	BOB	)	"	,	value:	"	BOB	"	}	,
    {	label:	"	Bosnia and Herzegovina	(	BAM	)	"	,	value:	"	BAM	"	}	,
    {	label:	"	Botswana	(	BWP	)	"	,	value:	"	BWP	"	}	,
    {	label:	"	Brazil	(	BRL	)	"	,	value:	"	BRL	"	}	,
    {	label:	"	Bulgaria	(	BGN	)	"	,	value:	"	BGN	"	}	,
    {	label:	"	Cabo Verde	(	CVE	)	"	,	value:	"	CVE	"	}	,
    {	label:	"	Cambodia	(	KHR	)	"	,	value:	"	KHR	"	}	,
    {	label:	"	Cameroon, Republic of	(	XAF	)	"	,	value:	"	XAF	"	}	,
    {	label:	"	Canada	(	CAD	)	"	,	value:	"	CAD	"	}	,
    {	label:	"	Cayman Islands	(	KYD	)	"	,	value:	"	KYD	"	}	,
    {	label:	"	Chad	(	XAF	)	"	,	value:	"	XAF	"	}	,
    {	label:	"	Chile	(	CLP	)	"	,	value:	"	CLP	"	}	,
    {	label:	"	China, People’s Republic of	(	CNY	)	"	,	value:	"	CNY	"	}	,
    {	label:	"	Colombia	(	COP	)	"	,	value:	"	COP	"	}	,
    {	label:	"	Congo, Democratic Republic of the	(	CDF	)	"	,	value:	"	CDF	"	}	,
    {	label:	"	Congo, Republic of	(	XAF	)	"	,	value:	"	XAF	"	}	,
    {	label:	"	Costa Rica	(	CRC	)	"	,	value:	"	CRC	"	}	,
    {	label:	"	Croatia	(	HRK	)	"	,	value:	"	HRK	"	}	,
    {	label:	"	Cyprus	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Czech Republic	(	CZK	)	"	,	value:	"	CZK	"	}	,
    {	label:	"	Denmark	(	DKK	)	"	,	value:	"	DKK	"	}	,
    {	label:	"	Dominican Republic	(	DOP	)	"	,	value:	"	DOP	"	}	,
    {	label:	"	Ecuador	(	USD	)	"	,	value:	"	USD	"	}	,
    {	label:	"	Egypt	(	EGP	)	"	,	value:	"	EGP	"	}	,
    {	label:	"	El Salvador	(	USD	)	"	,	value:	"	USD	"	}	,
    {	label:	"	Equatorial Guinea	(	XAF	)	"	,	value:	"	XAF	"	}	,
    {	label:	"	Estonia	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Ethiopia	(	ETB	)	"	,	value:	"	ETB	"	}	,
    {	label:	"	Fiji	(	FJD	)	"	,	value:	"	FJD	"	}	,
    {	label:	"	Finland	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	France	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Gabon	(	XAF	)	"	,	value:	"	XAF	"	}	,
    {	label:	"	Georgia	(	GEL	)	"	,	value:	"	GEL	"	}	,
    {	label:	"	Germany	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Ghana	(	GHS	)	"	,	value:	"	GHS	"	}	,
    {	label:	"	Gibraltar	(	GIP	)	"	,	value:	"	GIP	"	}	,
    {	label:	"	Greece	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Greenland	(	DKK	)	"	,	value:	"	DKK	"	}	,
    {	label:	"	Guatemala	(	GTQ	)	"	,	value:	"	GTQ	"	}	,
    {	label:	"	Guernsey, Channel Islands	(	GBP	)	"	,	value:	"	GBP	"	}	,
    {	label:	"	Guyana	(	GYD	)	"	,	value:	"	GYD	"	}	,
    {	label:	"	Honduras	(	HNL	)	"	,	value:	"	HNL	"	}	,
    {	label:	"	Hong Kong SAR	(	HKD	)	"	,	value:	"	HKD	"	}	,
    {	label:	"	Hungary	(	HUF	)	"	,	value:	"	HUF	"	}	,
    {	label:	"	Iceland	(	ISK	)	"	,	value:	"	ISK	"	}	,
    {	label:	"	India	(	INR	)	"	,	value:	"	INR	"	}	,
    {	label:	"	Indonesia	(	IDR	)	"	,	value:	"	IDR	"	}	,
    {	label:	"	Iraq	(	IQD	)	"	,	value:	"	IQD	"	}	,
    {	label:	"	Ireland	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Isle of Man	(	IMP	)	"	,	value:	"	IMP	"	}	,
    {	label:	"	Israel	(	ILS	)	"	,	value:	"	ILS	"	}	,
    {	label:	"	Italy	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Ivory Coast (Cote d'Ivoire)	(	XOF	)	"	,	value:	"	XOF	"	}	,
    {	label:	"	Jamaica	(	JMD	)	"	,	value:	"	JMD	"	}	,
    {	label:	"	Japan	(	JPY	)	"	,	value:	"	JPY	"	}	,
    {	label:	"	Jersey, Channel Islands	(	GBP	)	"	,	value:	"	GBP	"	}	,
    {	label:	"	Jordan	(	JOD	)	"	,	value:	"	JOD	"	}	,
    {	label:	"	Kazakhstan	(	KZT	)	"	,	value:	"	KZT	"	}	,
    {	label:	"	Kenya	(	KES	)	"	,	value:	"	KES	"	}	,
    {	label:	"	Korea, Republic of	(	KRW	)	"	,	value:	"	KRW	"	}	,
    {	label:	"	Kosovo	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Kuwait	(	KWD	)	"	,	value:	"	KWD	"	}	,
    {	label:	"	Kyrgyzstan	(	KGS	)	"	,	value:	"	KGS	"	}	,
    {	label:	"	Lao PDR	(	LAK	)	"	,	value:	"	LAK	"	}	,
    {	label:	"	Latvia	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Lebanon	(	LBP	)	"	,	value:	"	LBP	"	}	,
    {	label:	"	Libya	(	LYD	)	"	,	value:	"	LYD	"	}	,
    {	label:	"	Liechtenstein	(	CHF	)	"	,	value:	"	CHF	"	}	,
    {	label:	"	Lithuania	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Luxembourg	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Macau SAR	(	MOP	)	"	,	value:	"	MOP	"	}	,
    {	label:	"	Madagascar	(	MGA	)	"	,	value:	"	MGA	"	}	,
    {	label:	"	Malawi	(	MWK	)	"	,	value:	"	MWK	"	}	,
    {	label:	"	Malaysia	(	MYR	)	"	,	value:	"	MYR	"	}	,
    {	label:	"	Maldives, Republic of	(	MVR	)	"	,	value:	"	MVR	"	}	,
    {	label:	"	Malta	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Mauritania	(	MRU	)	"	,	value:	"	MRU	"	}	,
    {	label:	"	Mauritius	(	MUR	)	"	,	value:	"	MUR	"	}	,
    {	label:	"	Mexico	(	MXN	)	"	,	value:	"	MXN	"	}	,
    {	label:	"	Moldova	(	MDL	)	"	,	value:	"	MDL	"	}	,
    {	label:	"	Mongolia	(	MNT	)	"	,	value:	"	MNT	"	}	,
    {	label:	"	Montenegro	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Morocco	(	MAD	)	"	,	value:	"	MAD	"	}	,
    {	label:	"	Mozambique	(	MZN	)	"	,	value:	"	MZN	"	}	,
    {	label:	"	Myanmar	(	MMK	)	"	,	value:	"	MMK	"	}	,
    {	label:	"	Namibia, Republic of	(	NAD	)	"	,	value:	"	NAD	"	}	,
    {	label:	"	Netherlands	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	New Zealand	(	NZD	)	"	,	value:	"	NZD	"	}	,
    {	label:	"	Nicaragua	(	NIO	)	"	,	value:	"	NIO	"	}	,
    {	label:	"	Nigeria	(	NGN	)	"	,	value:	"	NGN	"	}	,
    {	label:	"	North Macedonia	(	MKD	)	"	,	value:	"	MKD	"	}	,
    {	label:	"	Norway	(	NOK	)	"	,	value:	"	NOK	"	}	,
    {	label:	"	Oman	(	OMR	)	"	,	value:	"	OMR	"	}	,
    {	label:	"	Pakistan	(	PKR	)	"	,	value:	"	PKR	"	}	,
    {	label:	"	Palestinian territories	(	ILS, USD, and JOD	)	"	,	value:	"	ILS, USD, and JOD	"	}	,
    {	label:	"	Panama	(	PAB  and USD	)	"	,	value:	"	PAB  and USD	"	}	,
    {	label:	"	Papua New Guinea	(	PGK	)	"	,	value:	"	PGK	"	}	,
    {	label:	"	Paraguay	(	PYG	)	"	,	value:	"	PYG	"	}	,
    {	label:	"	Peru	(	PEN	)	"	,	value:	"	PEN	"	}	,
    {	label:	"	Philippines	(	PHP	)	"	,	value:	"	PHP	"	}	,
    {	label:	"	Poland	(	PLN	)	"	,	value:	"	PLN	"	}	,
    {	label:	"	Portugal	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Puerto Rico	(	USD	)	"	,	value:	"	USD	"	}	,
    {	label:	"	Qatar	(	QAR	)	"	,	value:	"	QAR	"	}	,
    {	label:	"	Romania	(	RON	)	"	,	value:	"	RON	"	}	,
    {	label:	"	Russian Federation	(	RUB	)	"	,	value:	"	RUB	"	}	,
    {	label:	"	Rwanda	(	RWF	)	"	,	value:	"	RWF	"	}	,
    {	label:	"	Saint Lucia	(	XCD	)	"	,	value:	"	XCD	"	}	,
    {	label:	"	Saudi Arabia	(	SAR	)	"	,	value:	"	SAR	"	}	,
    {	label:	"	Senegal	(	XOF	)	"	,	value:	"	XOF	"	}	,
    {	label:	"	Serbia	(	RSD	)	"	,	value:	"	RSD	"	}	,
    {	label:	"	Singapore	(	SGD	)	"	,	value:	"	SGD	"	}	,
    {	label:	"	Slovak Republic	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Slovenia	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	South Africa	(	ZAR	)	"	,	value:	"	ZAR	"	}	,
    {	label:	"	Spain	(	EUR	)	"	,	value:	"	EUR	"	}	,
    {	label:	"	Sri Lanka	(	LKR	)	"	,	value:	"	LKR	"	}	,
    {	label:	"	Swaziland	(	SZL	)	"	,	value:	"	SZL	"	}	,
    {	label:	"	Sweden	(	SEK	)	"	,	value:	"	SEK	"	}	,
    {	label:	"	Switzerland	(	CHF	)	"	,	value:	"	CHF	"	}	,
    {	label:	"	Taiwan	(	TWD	)	"	,	value:	"	TWD	"	}	,
    {	label:	"	Tajikistan	(	TJS	)	"	,	value:	"	TJS	"	}	,
    {	label:	"	Tanzania	(	TZS	)	"	,	value:	"	TZS	"	}	,
    {	label:	"	Thailand	(	THB	)	"	,	value:	"	THB	"	}	,
    {	label:	"	Timor-Leste	(	USD	)	"	,	value:	"	USD	"	}	,
    {	label:	"	Trinidad And Tobago	(	TTD	)	"	,	value:	"	TTD	"	}	,
    {	label:	"	Tunisia	(	TND	)	"	,	value:	"	TND	"	}	,
    {	label:	"	Turkey	(	TRY	)	"	,	value:	"	TRY	"	}	,
    {	label:	"	Turkmenistan	(	TMT	)	"	,	value:	"	TMT	"	}	,
    {	label:	"	Uganda	(	UGX	)	"	,	value:	"	UGX	"	}	,
    {	label:	"	Ukraine	(	UAH	)	"	,	value:	"	UAH	"	}	,
    {	label:	"	United Arab Emirates	(	AED	)	"	,	value:	"	AED	"	}	,
    {	label:	"	United Kingdom	(	GBP	)	"	,	value:	"	GBP	"	}	,
    {	label:	"	United States	(	USD	)	"	,	value:	"	USD	"	}	,
    {	label:	"	Uruguay	(	UYU	)	"	,	value:	"	UYU	"	}	,
    {	label:	"	Uzbekistan, Republic of	(	UZS	)	"	,	value:	"	UZS	"	}	,
    {	label:	"	Venezuela	(	VEF	)	"	,	value:	"	VEF	"	}	,
    {	label:	"	Vietnam	(	VND	)	"	,	value:	"	VND	"	}	,
    {	label:	"	Zambia	(	ZMW	)	"	,	value:	"	ZMW	"	}	,
    {	label:	"	Zimbabwe	(	ZWD	)	"	,	value:	"	ZWD	"	}	,
    
]